import test from'node:test';import assert from'node:assert/strict';
import{MARTIAL_DATA,MARTIAL_BY_ID}from'../src/data/martial/index.js';import{MING_CORE_FACTION_BY_ID}from'../src/data/factions/ming/coreFactions.js';import{MING_CORE_NPC_BY_ID}from'../src/data/npcs/ming/index.js';import{MING_MARTIAL_MANUAL_BY_ID}from'../src/data/items/manuals/ming.js';
import{createCharacter}from'../src/player/characterFactory.js';import{createSession,trainMartialSession}from'../src/core/sessionFactory.js';import{hasMartial}from'../src/martial/state.js';import{learnMartial}from'../src/martial/learning.js';import{learnAtLuoyangHall,LUOYANG_BASIC_LESSON_COST}from'../src/martial/venues/luoyangHall.js';
const BASE={root:60,insight:60,physique:60,agility:60,will:60,fortune:50,charm:50};

test('M7首批武学扩展到30门且ID唯一',()=>{assert.equal(MARTIAL_DATA.length,30);assert.equal(new Set(MARTIAL_DATA.map(x=>x.id)).size,30)});
test('所有武学前置与来源引用都可解析',()=>{for(const m of MARTIAL_DATA){for(const id of m.requirements?.prerequisites||[])assert.ok(MARTIAL_BY_ID[id],`${m.id} prerequisite ${id}`);for(const s of m.learnSources||[]){if(s.factionId)assert.ok(MING_CORE_FACTION_BY_ID[s.factionId],`${m.id} faction ${s.factionId}`);if(s.npcId)assert.ok(MING_CORE_NPC_BY_ID[s.npcId],`${m.id} npc ${s.npcId}`);if(s.itemId){const manual=MING_MARTIAL_MANUAL_BY_ID[s.itemId];assert.ok(manual,`${m.id} manual ${s.itemId}`);assert.equal(manual.martialId,m.id,`${s.itemId} should teach ${m.id}`)}}}});
test('高阶武学不能通过普通commonAccess白送',()=>{for(const m of MARTIAL_DATA.filter(x=>!['入门'].includes(x.grade)))assert.ok(!(m.learnSources||[]).some(x=>x.type==='common'),m.id)});
test('体系占位明确标记aggregate避免冒充原著单一招式',()=>{assert.equal(MARTIAL_BY_ID.martial_huashan_sword_branch_methods.aggregate,true);assert.equal(MARTIAL_BY_ID.martial_sunmoon_advanced_movement.aggregate,true)});
test('武馆少主真实拥有基础拳与基础剑',()=>{const s=createSession(createCharacter({originId:'dojo_heir',baseAttributes:BASE}));assert.ok(hasMartial(s.character,'martial_basic_fist'));assert.ok(hasMartial(s.character,'martial_basic_sword'))});
test('洛阳武馆学习会扣银并推进一小时',()=>{let s=createSession(createCharacter({originId:'hunter',baseAttributes:BASE}));s={...s,character:{...s.character,world:{...s.character.world,scene:'ming_luoyang_martial_hall'}}};const before=s.character.wallet.silver;s=learnAtLuoyangHall(s,'martial_basic_fist');assert.ok(hasMartial(s.character,'martial_basic_fist'));assert.equal(s.character.wallet.silver,before-LUOYANG_BASIC_LESSON_COST);assert.equal(s.character.world.hour,9)});
test('不在洛阳武馆不能凭空学基础武功',()=>{const s=createSession(createCharacter({originId:'hunter',baseAttributes:BASE}));assert.throws(()=>learnAtLuoyangHall(s,'martial_basic_fist'),/not_at_luoyang_hall/)});
test('天生剑骨实际加快剑法修炼',()=>{const normal=createSession(createCharacter({originId:'dojo_heir',baseAttributes:BASE}));const gifted=createSession(createCharacter({originId:'dojo_heir',talentId:'sword_bone',baseAttributes:BASE}));const a=trainMartialSession(normal,'martial_basic_sword',2),b=trainMartialSession(gifted,'martial_basic_sword',2);assert.ok(b.result.masteryGain>a.result.masteryGain)});
test('练功推进江湖时间和NPC日程',()=>{const s=createSession(createCharacter({originId:'dojo_heir',baseAttributes:BASE}));const out=trainMartialSession(s,'martial_basic_sword',4);assert.equal(out.session.character.world.hour,12);assert.equal(out.session.worldState.npc.states.npc_linghu_chong.sceneId,'ming_huashan_cliff')});
test('紫霞神功同时检查前置、属性和师承关系',()=>{let c=createCharacter({originId:'hunter',baseAttributes:{root:75,insight:75,physique:70,agility:70,will:75,fortune:50,charm:50}});c=learnMartial(c,'martial_huashan_basic_sword',{teacherId:'npc_linghu_chong',teacherRelation:0});assert.throws(()=>learnMartial(c,'martial_zixia_gong',{teacherId:'npc_yue_buqun',teacherRelation:59}),/no_valid_source/);c=learnMartial(c,'martial_zixia_gong',{teacherId:'npc_yue_buqun',teacherRelation:60});assert.ok(hasMartial(c,'martial_zixia_gong'))});
test('阿鼻道三刀必须先掌握雄霸天下',()=>{let c=createCharacter({originId:'dojo_heir',baseAttributes:{root:80,insight:75,physique:80,agility:75,will:80,fortune:50,charm:50}});assert.throws(()=>learnMartial(c,'martial_abi_three_sabers',{manualIds:['manual_abi_three_sabers']}),/missing_prerequisite_martial_xiongba_tianxia/)});
