import {ATTRIBUTE_DEFS,rollBaseAttributes} from '../data/attributes.js';
import {ORIGINS,ORIGIN_BY_ID} from '../data/origins.js';
import {TALENTS,TALENT_BY_ID} from '../data/talents.js';
import {createCharacter,previewCharacter} from '../player/characterFactory.js';
import {deleteSlot,getSlots,loadCharacter,saveCharacter} from '../save/saveManager.js';
import {formatOriginGrant} from './originGrantView.js';

const state={base:rollBaseAttributes(),originId:null,talentId:null,slot:0};
const $=q=>document.querySelector(q);
function modifiersText(modifiers){return Object.entries(modifiers).map(([id,value])=>`${ATTRIBUTE_DEFS.find(a=>a.id===id)?.name||id}${value>=0?'+':''}${value}`).join(' · ')||'无直接属性修正';}
function renderAttributes(){$('#attributes').innerHTML=ATTRIBUTE_DEFS.map(a=>`<div class="attr"><span>${a.name}</span><b>${state.base[a.id]}</b></div>`).join('');}
function renderOrigins(){$('#origins').innerHTML=ORIGINS.map(origin=>`<button class="card ${state.originId===origin.id?'selected':''}" data-origin="${origin.id}"><b>${origin.name}<span>${origin.tier}</span></b><small>${origin.summary}</small><small>${modifiersText(origin.modifiers)}</small><small class="grant">${formatOriginGrant(origin.grant)}</small></button>`).join('');}
function renderTalents(){const none=`<button class="card ${state.talentId===null?'selected':''}" data-talent=""><b>凡骨<span>无外挂</span></b><small>完全不用外挂，以普通人的方式闯江湖。</small></button>`;$('#talents').innerHTML=none+TALENTS.map(talent=>`<button class="card talent-card ${state.talentId===talent.id?'selected':''}" data-talent="${talent.id}"><b>${talent.name}<span>唯一</span></b><small>${talent.summary}</small><strong class="talent-runtime">真实机制：${talent.runtimeText}</strong><small>基础属性：${modifiersText(talent.modifiers)}</small></button>`).join('');}
function renderSummary(){const name=$('#character-name').value.trim()||'无名氏',origin=state.originId?ORIGIN_BY_ID[state.originId]:null,talent=state.talentId?TALENT_BY_ID[state.talentId]:null;$('#summary-name').textContent=name;$('#summary-origin').textContent=origin?`${origin.name} · ${origin.tier}`:'尚未选择出身';$('#summary-talent').textContent=talent?`${talent.name} · ${talent.runtimeText}`:'凡骨 · 无外挂';$('#summary-grant').textContent=origin?formatOriginGrant(origin.grant):'选择出身后显示起始资源';const finalAttributes=origin?previewCharacter(state.base,state.originId,state.talentId):state.base;$('#final-attributes').innerHTML=ATTRIBUTE_DEFS.map(a=>`<div class="stat"><span>${a.name}</span><b>${finalAttributes[a.id]}</b></div>`).join('');}
function renderEnterState(){const character=getSlots()[state.slot];$('#enter-world').disabled=!character;$('#enter-world').textContent=character?`进入大明 · ${character.name}`:'进入大明';}
function renderSlots(){const slots=getSlots();$('#save-slots').innerHTML=slots.map((character,index)=>`<div class="slot-row"><button class="slot ${state.slot===index?'selected':''}" data-slot="${index}">档${index+1}${character?` · ${character.name}`:' · 空'}</button>${character?`<button class="slot-action" data-load="${index}">查看</button><button class="slot-action danger" data-delete="${index}">删除</button>`:''}</div>`).join('');renderEnterState();}
function render(){renderAttributes();renderOrigins();renderTalents();renderSummary();renderSlots();}
export function initCharacterCreation(){render();$('#reroll').onclick=()=>{state.base=rollBaseAttributes();renderAttributes();renderSummary();};$('#character-name').oninput=renderSummary;$('#origins').onclick=event=>{const button=event.target.closest('[data-origin]');if(!button)return;state.originId=button.dataset.origin;renderOrigins();renderSummary();};$('#talents').onclick=event=>{const button=event.target.closest('[data-talent]');if(!button)return;state.talentId=button.dataset.talent||null;renderTalents();renderSummary();};$('#save-slots').onclick=event=>{const select=event.target.closest('[data-slot]');if(select){state.slot=Number(select.dataset.slot);renderSlots();return;}const load=event.target.closest('[data-load]');if(load){const character=loadCharacter(Number(load.dataset.load));$('#status-line').textContent=character?`${character.name}｜${ORIGIN_BY_ID[character.originId]?.name||character.originId}｜${character.talentId?(TALENT_BY_ID[character.talentId]?.name||character.talentId):'无外挂'}｜银两 ${character.wallet?.silver??0}`:'该档位为空。';return;}const remove=event.target.closest('[data-delete]');if(remove){deleteSlot(Number(remove.dataset.delete));renderSlots();$('#status-line').textContent='档位已删除。';}};$('#confirm-character').onclick=()=>{const line=$('#status-line');if(!state.originId){line.textContent='还没有选择出身。';return;}const character=createCharacter({name:$('#character-name').value,originId:state.originId,talentId:state.talentId,baseAttributes:state.base});saveCharacter(state.slot,character);renderSlots();line.textContent=`${character.name} 已写入档位 ${state.slot+1}，可以进入大明。`;};$('#enter-world').onclick=()=>{if(!loadCharacter(state.slot))return;document.dispatchEvent(new CustomEvent('jiuzhou:enter-world',{detail:{slot:state.slot}}));};}
