import {MARTIAL_DATA}from'../data/martial/index.js';
import {hasMartial,masteryStage}from'../martial/state.js';
import {canUseLuoyangHall,LUOYANG_BASIC_LESSON_COST,LUOYANG_BASIC_MARTIAL_IDS}from'../martial/venues/luoyangHall.js';

const ATTR_NAMES={root:'根骨',insight:'悟性',physique:'体魄',agility:'身法',will:'定力',fortune:'福缘',charm:'魅力'};
function requirementText(martial){const attrs=Object.entries(martial.requirements?.attributes||{}).map(([id,value])=>`${ATTR_NAMES[id]||id}≥${value}`);const pre=(martial.requirements?.prerequisites||[]).map(id=>`前置：${id}`);return[...attrs,...pre].join(' · ')||'无属性门槛';}
function learnedCard(character,martial){const entry=character.martialState.learned[martial.id];return`<article class="martial-card learned"><div><span>${martial.grade} · ${martial.category}</span><h3>${martial.name}</h3></div><p>${martial.summary}</p><div class="martial-progress"><b>${masteryStage(entry.mastery)}</b><span>熟练 ${entry.mastery}/10000</span><span>理解 ${entry.understanding}/100</span><span>累计修炼 ${entry.trainingHours} 小时</span></div><button data-train="${martial.id}">修炼 2 小时</button></article>`;}
function lockedCard(session,martial){const basic=LUOYANG_BASIC_MARTIAL_IDS.includes(martial.id),atHall=canUseLuoyangHall(session);return`<article class="martial-card locked"><div><span>${martial.grade} · ${martial.category}</span><h3>${martial.name}</h3></div><p>${martial.summary}</p><small>${requirementText(martial)}</small>${basic?`<p>${atHall?`洛阳武馆普通教习可传授，束脩 ${LUOYANG_BASIC_LESSON_COST} 两。`:'前往 洛阳 → 武馆街，可向普通教习学习。'}</p><button data-learn="${martial.id}" ${atHall?'':'disabled'}>学习此武功</button>`:'<p>需要对应师承、门派关系或秘籍，当前不会白送。</p>'}</article>`;}
export function renderMartialPanel(container,session,{onTrain,onLearn,onBack,message=''}){const character=session.character;container.innerHTML=`<div class="section-head"><div><p class="eyebrow">武学</p><h2>所学与传承</h2><p>武功不是战力数字包。每门武学分别记录熟练、理解与传承门槛。</p></div><button data-martial-back>返回江湖</button></div>${message?`<p class="martial-message">${message}</p>`:''}<div class="martial-grid">${MARTIAL_DATA.map(m=>hasMartial(character,m.id)?learnedCard(character,m):lockedCard(session,m)).join('')}</div>`;container.querySelector('[data-martial-back]').onclick=onBack;container.querySelectorAll('[data-train]').forEach(b=>b.onclick=()=>onTrain(b.dataset.train));container.querySelectorAll('[data-learn]').forEach(b=>b.onclick=()=>onLearn(b.dataset.learn));}
