import {MING_COUNTRY} from '../data/countries/ming.js';
import {MING_LOCATIONS,MING_LOCATION_BY_ID} from '../data/locations/ming/index.js';
import {findShortestRoute} from '../world/routePlanner.js';
import {ensureSession,syncSessionWorld,travelSession,trainMartialSession,interveneEventSession} from '../core/sessionFactory.js';
import {learnAtLuoyangHall} from '../martial/venues/luoyangHall.js';
import {talkToNpc} from '../npc/interactions.js';
import {loadSession,saveSession} from '../save/saveManager.js';
import {renderMartialPanel} from './martialPanel.js';
import {mountCombatPrototype} from './combatPrototype.js';
import {renderEventPanel} from './eventPanel.js';
import {canUseLuoyangSparring} from './locationFeatures.js';
import {renderNpcPanel,bindNpcPanel} from './npcPanel.js';

const OTHER_COUNTRIES=['大唐','大宋','大清','大理','辽','西夏','蒙古','神州','西域诸国','海外'];
const state={slot:0,session:null,view:'world',focusLocationId:null,returnView:'country',martialMessage:'',eventMessage:'',npcMessage:''};
const $=q=>document.querySelector(q),character=()=>state.session.character;
function currentLocation(){return MING_LOCATION_BY_ID[character()?.world?.location]||null;}
function formatTime(){const w=character().world;return `第 ${w.day} 日 · ${String(w.hour).padStart(2,'0')}:00`;}
function routeText(location){if(location.id===character().world.location)return'当前所在';const route=findShortestRoute(character().world.location,location.id);return route?`约 ${route.hours} 小时`:'道路未通';}
function persist(){saveSession(state.slot,state.session);}
function errorText(error){const map={not_at_luoyang_hall:'你不在洛阳武馆街。',martial_not_taught_here:'这里不传这门武功。',already_learned:'这门武功你已经会了。',not_enough_silver:'银两不够。',martial_not_learned:'尚未学会这门武功。',unknown_event:'这条江湖大事不存在。',unknown_intervention:'这个干预机会已经不存在。',intervention_not_available_in_phase:'局势已经变化，这个机会错过了。',intervention_wrong_location:'你必须亲自到对应地点才能插手。',unknown_npc:'这个人已经不在当前世界状态里。',npc_dead:'此人已经死亡。',npc_not_discovered:'你还不知道此人的存在。',npc_not_in_same_scene:'你与此人并不在同一场景。'};return map[error?.message]||`无法执行：${error?.message||'未知原因'}`;}

function renderShell(){const root=$('#world-root');root.hidden=false;$('#creation-root').hidden=true;root.innerHTML=`<section class="world-top panel"><div><p class="eyebrow">九州武侠 · M9</p><h1 id="world-character-name"></h1><p id="world-character-meta"></p></div><div class="world-status"><b id="world-location"></b><span id="world-time"></span><span id="world-silver"></span></div></section><nav class="world-nav panel"><button data-world-home>天下列国</button><button data-country="ming">大明</button><button data-martial>武学</button><button data-events>江湖志</button><button data-return-create>返回角色页</button></nav><section id="world-content" class="panel world-content"></section>`;root.querySelector('#world-character-name').textContent=character().name;root.querySelector('#world-character-meta').textContent='江湖初行 · 大明';root.querySelector('[data-world-home]').onclick=()=>{state.view='world';state.focusLocationId=null;renderContent();};root.querySelector('[data-country]').onclick=()=>{state.view='country';state.focusLocationId=null;renderContent();};root.querySelector('[data-martial]').onclick=()=>{state.returnView=state.view==='martial'?'country':state.view;state.view='martial';state.martialMessage='';renderContent();};root.querySelector('[data-events]').onclick=()=>{state.returnView=['events','combat'].includes(state.view)?'country':state.view;state.view='events';state.eventMessage='';renderContent();};root.querySelector('[data-return-create]').onclick=()=>{root.hidden=true;$('#creation-root').hidden=false;};renderContent();}
function renderHeader(){const loc=currentLocation();$('#world-location').textContent=loc?`当前位置：${loc.name}`:'当前位置：未知';$('#world-time').textContent=formatTime();$('#world-silver').textContent=`银两：${character().wallet?.silver??0}`;}
function renderWorld(){const content=$('#world-content');content.innerHTML=`<div class="section-head"><div><p class="eyebrow">天下列国图</p><h2>天下</h2><p>各国同时存在于这个架空融合时代。V0.1 先把大明做活，其余国域暂不开放。</p></div></div><div class="country-grid"><button class="country-card active-country" data-open-ming><b>大明</b><span>已开放 · 当前首发国域</span></button>${OTHER_COUNTRIES.map(name=>`<button class="country-card" disabled><b>${name}</b><span>后续开放</span></button>`).join('')}</div>`;content.querySelector('[data-open-ming]').onclick=()=>{state.view='country';renderContent();};}
function renderCountry(){const content=$('#world-content');content.innerHTML=`<div class="section-head"><div><p class="eyebrow">国域</p><h2>${MING_COUNTRY.name}</h2><p>${MING_COUNTRY.description}</p></div></div><div class="location-grid">${MING_LOCATIONS.map(loc=>`<button class="location-card ${loc.id===character().world.location?'current':''}" data-location="${loc.id}"><span class="risk">风险 ${loc.risk}</span><b>${loc.name}</b><small>${loc.summary}</small><em>${routeText(loc)}</em></button>`).join('')}</div>`;content.querySelectorAll('[data-location]').forEach(button=>button.onclick=()=>{state.focusLocationId=button.dataset.location;state.view='location';state.npcMessage='';renderContent();});}
function sparringBlock(){if(!canUseLuoyangSparring(character()))return'';return'<div class="travel-box"><b>武馆演武场</b><span>用你真正学会的基础武功与教习切磋。战斗使用Canvas动态表现。</span><button data-open-combat>切磋试招</button></div>';}
function renderLocation(){const location=MING_LOCATION_BY_ID[state.focusLocationId];if(!location){state.view='country';renderContent();return;}const here=location.id===character().world.location,route=here?{hours:0,locations:[location.id]}:findShortestRoute(character().world.location,location.id),content=$('#world-content');content.innerHTML=`<div class="section-head"><div><p class="eyebrow">${location.kind}</p><h2>${location.name}</h2><p>${location.summary}</p></div><button data-back-country>返回大明地图</button></div>${here?'<p class="arrival">你当前就在这里。</p>':`<div class="travel-box"><b>行程：${route?route.locations.map(id=>MING_LOCATION_BY_ID[id]?.name||id).join(' → '):'道路未通'}</b><span>${route?`预计 ${route.hours} 小时`:'暂不可达'}</span><button data-travel ${route?'':'disabled'}>启程前往</button></div>`}<div class="scene-grid">${here?location.scenes.map(scene=>`<button data-scene="${scene.id}" class="${character().world.scene===scene.id?'selected-scene':''}"><b>${scene.name}</b><span>进入场景</span></button>`).join(''):'<p>抵达后才能进入具体场景。</p>'}</div>${here?sparringBlock():''}${here?renderNpcPanel(location,state.session,{message:state.npcMessage}):''}`;content.querySelector('[data-back-country]').onclick=()=>{state.view='country';state.npcMessage='';renderContent();};const travel=content.querySelector('[data-travel]');if(travel)travel.onclick=()=>{state.session=travelSession(state.session,location.id);state.npcMessage='';persist();renderContent();};content.querySelectorAll('[data-scene]').forEach(button=>button.onclick=()=>{state.session={...state.session,character:{...character(),world:{...character().world,scene:button.dataset.scene}}};state.npcMessage='';persist();renderContent();});bindNpcPanel(content,npcId=>{try{const out=talkToNpc(state.session,npcId);state.session=out.session;state.npcMessage=out.result.message;persist();}catch(error){state.npcMessage=errorText(error);}renderContent();});const combat=content.querySelector('[data-open-combat]');if(combat)combat.onclick=()=>{state.view='combat';renderContent();};}
function renderMartial(){const content=$('#world-content');renderMartialPanel(content,state.session,{message:state.martialMessage,onBack:()=>{state.view=state.returnView==='martial'?'country':state.returnView;renderContent();},onLearn:id=>{try{state.session=learnAtLuoyangHall(state.session,id);state.martialMessage='教习传授了基础法门。一个时辰过去，江湖也没有停下。';persist();}catch(error){state.martialMessage=errorText(error);}renderContent();},onTrain:id=>{try{const out=trainMartialSession(state.session,id,2);state.session=out.session;state.martialMessage=`修炼两小时：熟练 +${out.result.masteryGain}，理解 +${out.result.understandingGain}。`;persist();}catch(error){state.martialMessage=errorText(error);}renderContent();}});}
function renderEvents(){const content=$('#world-content');renderEventPanel(content,state.session,{message:state.eventMessage,onBack:()=>{state.view=['events','combat'].includes(state.returnView)?'country':state.returnView;renderContent();},onIntervene:(eventId,interventionId)=>{try{state.session=interveneEventSession(state.session,eventId,interventionId);state.eventMessage='你已经插手此事。江湖局势随之发生变化。';persist();}catch(error){state.eventMessage=errorText(error);}renderContent();}});}
function renderCombat(){const content=$('#world-content');mountCombatPrototype(content,state.session,{onBack:()=>{state.view='location';renderContent();},onFinish:next=>{state.session=next;persist();state.view='location';renderContent();}});}
function renderContent(){renderHeader();if(state.view==='world')renderWorld();else if(state.view==='country')renderCountry();else if(state.view==='martial')renderMartial();else if(state.view==='events')renderEvents();else if(state.view==='combat')renderCombat();else renderLocation();}
export function initWorldMap(slot){const loaded=loadSession(slot);if(!loaded)throw Error('empty_slot');state.slot=slot;state.session=syncSessionWorld(ensureSession(loaded));persist();state.view='world';state.focusLocationId=null;state.martialMessage='';state.eventMessage='';state.npcMessage='';renderShell();}
