import {MING_COUNTRY} from '../data/countries/ming.js';
import {MING_LOCATIONS,MING_LOCATION_BY_ID} from '../data/locations/ming/index.js';
import {findShortestRoute} from '../world/routePlanner.js';
import {ensureSession,syncSessionWorld,travelSession,trainMartialSession,interveneEventSession} from '../core/sessionFactory.js';
import {learnAtLuoyangHall} from '../martial/venues/luoyangHall.js';
import {talkToNpc} from '../npc/interactions.js';
import {loadSession,saveSession} from '../save/saveManager.js';
import {renderMartialPanel} from './martialPanel.js';
import {renderMartialAtlas}from'./martialAtlas.js';
import {renderCharacterPanel}from'./characterPanel.js';
import {mountCombatPrototype} from './combatPrototype.js';
import {renderEventPanel} from './eventPanel.js';
import {canUseLuoyangSparring} from './locationFeatures.js';
import {renderNpcPanel,bindNpcPanel} from './npcPanel.js';
import {renderSceneEventPanel,bindSceneEventPanel}from'./sceneEventPanel.js';
import {renderVenuePanel,bindVenuePanel}from'./venuePanel.js';
import {renderEncounterPanel}from'./encounterPanel.js';
import {characterVitals}from'../player/progression.js';

const OTHER_COUNTRIES=['大唐','大宋','大清','大理','辽','西夏','蒙古','神州','西域诸国','海外'];
const state={slot:0,session:null,view:'world',focusLocationId:null,returnView:'world',martialMessage:'',locationMessage:'',npcMessage:'',combatEncounterId:null};
const $=q=>document.querySelector(q),character=()=>state.session.character;
function currentLocation(){return MING_LOCATION_BY_ID[character()?.world?.location]||null;}
function formatTime(){const w=character().world;return`第 ${w.day} 日 · ${String(w.hour).padStart(2,'0')}:00`;}
function routeText(location){if(location.id===character().world.location)return'当前所在';const route=findShortestRoute(character().world.location,location.id);return route?`约 ${route.hours} 小时`:'道路未通';}
function persist(){saveSession(state.slot,state.session);}
function errorText(error){const map={not_at_luoyang_hall:'你不在洛阳武馆街。',martial_not_taught_here:'这里不传这门武功。',already_learned:'这门武功你已经会了。',not_enough_silver:'银两不够。',martial_not_learned:'尚未学会这门武功。',unknown_event:'这条江湖大事不存在。',unknown_intervention:'这个干预机会已经不存在。',intervention_not_available_in_phase:'局势已经变化，这个机会错过了。',intervention_wrong_location:'你必须亲自到对应地点才能插手。',event_npc_unavailable:'相关人物现在不在这里，等他出现再谈。',unknown_npc:'这个人已经不在当前世界状态里。',npc_dead:'此人已经死亡。',npc_not_discovered:'你还不知道此人的存在。',npc_not_in_same_scene:'你与此人并不在同一场景。'};return map[error?.message]||`无法执行：${error?.message||'未知原因'}`;}
function navTo(view){state.returnView=state.view;state.view=view;state.martialMessage='';renderContent();}
function renderShell(){const root=$('#world-root');root.hidden=false;$('#creation-root').hidden=true;root.innerHTML=`<section class="world-top panel"><div class="world-identity"><p class="eyebrow">九州武侠 · 大明</p><h1 id="world-character-name"></h1><p id="world-character-meta"></p></div><div class="world-quick" id="world-quick"></div></section><nav class="world-nav panel"><button data-world-home>天下</button><button data-character>人物</button><button data-martial>武学</button><button data-events>江湖志</button></nav><section id="world-content" class="panel world-content"></section>`;root.querySelector('#world-character-name').textContent=character().name;root.querySelector('[data-world-home]').onclick=()=>{state.view='world';state.focusLocationId=null;renderContent();};root.querySelector('[data-character]').onclick=()=>navTo('character');root.querySelector('[data-martial]').onclick=()=>navTo('martial');root.querySelector('[data-events]').onclick=()=>navTo('events');renderContent();}
function renderHeader(){const loc=currentLocation(),v=characterVitals(character());$('#world-character-meta').textContent=`${v.rank.name} · ${v.inner.name}`;$('#world-quick').innerHTML=`<div><span>气血</span><b>${v.maxHp}</b></div><div><span>内力</span><b>${v.maxQi}</b></div><div><span>江湖层级</span><b>${v.rank.name}</b></div><div><span>内功</span><b>${v.inner.name}</b></div><div class="wide"><span>位置</span><b>${loc?.name||'未知'}${character().world.scene?` · ${loc?.scenes.find(x=>x.id===character().world.scene)?.name||''}`:''}</b></div><div><span>时间</span><b>${formatTime()}</b></div><div><span>银两</span><b>${character().wallet?.silver??0}</b></div>`;}
function renderWorld(){const content=$('#world-content');content.innerHTML=`<div class="section-head"><div><p class="eyebrow">天下列国图</p><h2>天下</h2><p>国家是最高层地图。进入大明后，再选择城市、门派与具体场景。</p></div></div><div class="country-grid"><button class="country-card active-country" data-open-ming><b>大明</b><span>已开放 · 当前首发国域</span></button>${OTHER_COUNTRIES.map(name=>`<button class="country-card" disabled><b>${name}</b><span>后续开放</span></button>`).join('')}</div>`;content.querySelector('[data-open-ming]').onclick=()=>{state.view='country';renderContent();};}
function renderCountry(){const content=$('#world-content');content.innerHTML=`<div class="section-head"><div><p class="eyebrow">国域</p><h2>${MING_COUNTRY.name}</h2><p>${MING_COUNTRY.description}</p></div><button data-back-world>返回天下</button></div><div class="location-grid">${MING_LOCATIONS.map(loc=>`<button class="location-card ${loc.id===character().world.location?'current':''}" data-location="${loc.id}"><span class="risk">风险 ${loc.risk}</span><b>${loc.name}</b><small>${loc.summary}</small><em>${routeText(loc)}</em></button>`).join('')}</div>`;content.querySelector('[data-back-world]').onclick=()=>{state.view='world';renderContent();};content.querySelectorAll('[data-location]').forEach(button=>button.onclick=()=>{state.focusLocationId=button.dataset.location;state.view='location';state.locationMessage='';state.npcMessage='';renderContent();});}
function sparringBlock(){if(!canUseLuoyangSparring(character()))return'';return'<section class="encounter-panel"><p class="eyebrow">武馆切磋</p><h3>洛阳武馆演武场</h3><p>与教习切磋，同样会让你实际使用的武功增长熟练。</p><button data-open-combat>切磋试招</button></section>';}
function localActionResult(text){state.locationMessage=text;persist();renderContent();}
function doIntervention(eventId,interventionId){try{state.session=interveneEventSession(state.session,eventId,interventionId);localActionResult('你已经当场介入此事，江湖局势随之变化。');}catch(error){state.locationMessage=errorText(error);renderContent();}}
function renderLocation(){const location=MING_LOCATION_BY_ID[state.focusLocationId];if(!location){state.view='country';renderContent();return;}const here=location.id===character().world.location,route=here?{hours:0,locations:[location.id]}:findShortestRoute(character().world.location,location.id),content=$('#world-content');content.innerHTML=`<div class="section-head"><div><p class="eyebrow">${location.kind}</p><h2>${location.name}</h2><p>${location.summary}</p></div><button data-back-country>返回大明地图</button></div>${state.locationMessage?`<p class="location-message">${state.locationMessage}</p>`:''}${here?'<p class="arrival">你当前就在这里。</p>':`<div class="travel-box"><b>行程：${route?route.locations.map(id=>MING_LOCATION_BY_ID[id]?.name||id).join(' → '):'道路未通'}</b><span>${route?`预计 ${route.hours} 小时`:'暂不可达'}</span><button data-travel ${route?'':'disabled'}>启程前往</button></div>`}<div class="scene-grid">${here?location.scenes.map(scene=>`<button data-scene="${scene.id}" class="${character().world.scene===scene.id?'selected-scene':''}"><b>${scene.name}</b><span>进入场景</span></button>`).join(''):'<p>抵达后才能进入具体场景。</p>'}</div>${here?renderVenuePanel(state.session):''}${here?sparringBlock():''}${here?renderEncounterPanel(character()):''}${here?renderSceneEventPanel(state.session):''}${here?renderNpcPanel(location,state.session,{message:state.npcMessage}):''}`;content.querySelector('[data-back-country]').onclick=()=>{state.view='country';state.locationMessage='';state.npcMessage='';renderContent();};const travel=content.querySelector('[data-travel]');if(travel)travel.onclick=()=>{state.session=travelSession(state.session,location.id);state.locationMessage='';state.npcMessage='';persist();renderContent();};content.querySelectorAll('[data-scene]').forEach(button=>button.onclick=()=>{state.session={...state.session,character:{...character(),world:{...character().world,scene:button.dataset.scene}}};state.locationMessage='';state.npcMessage='';persist();renderContent();});bindVenuePanel(content,id=>{try{state.session=learnAtLuoyangHall(state.session,id);localActionResult('教习正式传下基础法门。一个时辰过去，江湖也在继续。');}catch(error){state.locationMessage=errorText(error);renderContent();}});bindSceneEventPanel(content,doIntervention);bindNpcPanel(content,{onTalk:npcId=>{try{const out=talkToNpc(state.session,npcId);state.session=out.session;state.npcMessage=out.result.message;persist();}catch(error){state.npcMessage=errorText(error);}renderContent();},onIntervene:doIntervention});const combat=content.querySelector('[data-open-combat]');if(combat)combat.onclick=()=>{state.combatEncounterId=null;state.view='combat';renderContent();};const encounter=content.querySelector('[data-start-encounter]');if(encounter)encounter.onclick=()=>{state.combatEncounterId=encounter.dataset.startEncounter;state.view='combat';renderContent();};}
function renderMartial(){const content=$('#world-content');renderMartialPanel(content,state.session,{message:state.martialMessage,onBack:()=>{state.view=state.returnView==='martial'?'world':state.returnView;renderContent();},onAtlas:()=>{state.view='martial-atlas';renderContent();},onTrain:id=>{try{const before=characterVitals(character()),out=trainMartialSession(state.session,id,24);state.session=out.session;const after=characterVitals(character());state.martialMessage=`闭门修炼一天：熟练 +${out.result.masteryGain}，理解 +${out.result.understandingGain}。${after.inner.id!==before.inner.id?` 内功突破至「${after.inner.name}」。`:''}${after.rank.id!==before.rank.id?` 江湖层级提升至「${after.rank.name}」。`:''}`;persist();}catch(error){state.martialMessage=errorText(error);}renderContent();}});}
function renderAtlas(){renderMartialAtlas($('#world-content'),character(),{onBack:()=>{state.view='martial';renderContent();}});}
function renderCharacter(){renderCharacterPanel($('#world-content'),character(),{onBack:()=>{state.view=state.returnView==='character'?'world':state.returnView;renderContent();}});}
function renderEvents(){renderEventPanel($('#world-content'),state.session,{onBack:()=>{state.view=state.returnView==='events'?'world':state.returnView;renderContent();}});}
function renderCombat(){mountCombatPrototype($('#world-content'),state.session,{encounterId:state.combatEncounterId,onBack:()=>{state.view='location';renderContent();},onFinish:(next,result)=>{state.session=next;persist();state.locationMessage=result?.won?(result.encounterId?'实战取胜。所用武功获得实战成长，江湖时间过去1小时。':'切磋结束。所用武功获得实战成长，过去1小时。'):(result?.metamorphosed?'虽然落败，但「生死蜕变」触发，根骨与定力永久增长。':'本场落败，但实战经验已经留下。');state.combatEncounterId=null;state.view='location';renderContent();}});}
function renderContent(){renderHeader();if(state.view==='world')renderWorld();else if(state.view==='country')renderCountry();else if(state.view==='character')renderCharacter();else if(state.view==='martial')renderMartial();else if(state.view==='martial-atlas')renderAtlas();else if(state.view==='events')renderEvents();else if(state.view==='combat')renderCombat();else renderLocation();}
export function initWorldMap(slot){const loaded=loadSession(slot);if(!loaded)throw Error('empty_slot');state.slot=slot;state.session=syncSessionWorld(ensureSession(loaded));persist();state.view='world';state.focusLocationId=null;state.martialMessage='';state.locationMessage='';state.npcMessage='';state.combatEncounterId=null;renderShell();}
