import{clamp,ease,lerp}from'./assets.js';
export class Effects{
 constructor(){this.particles=[];this.rings=[];this.numbers=[];this.shake=0;this.flash=0;this.hitstop=0;}
 clear(){this.particles=[];this.rings=[];this.numbers=[];this.shake=0;this.flash=0;this.hitstop=0;}
 burst(x,y,n=30,color='gold',power=1){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,v=(70+Math.random()*260)*power;this.particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v-60,life:.4+Math.random()*.55,max:1,color,size:1+Math.random()*3});}if(this.particles.length>550)this.particles.splice(0,this.particles.length-550);}
 ring(x,y,color='gold',max=180){this.rings.push({x,y,color,r:0,max,life:.7});}
 damage(x,y,n,color='gold'){this.numbers.push({x,y,n,life:1.1,color});}
 update(dt){this.shake*=Math.exp(-8*dt);this.flash=Math.max(0,this.flash-dt*2.5);this.hitstop=Math.max(0,this.hitstop-dt);for(const p of this.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=140*dt;p.life-=dt;}this.particles=this.particles.filter(p=>p.life>0);for(const r of this.rings){r.r+=r.max*dt*1.5;r.life-=dt;}this.rings=this.rings.filter(r=>r.life>0);for(const n of this.numbers){n.y-=65*dt;n.life-=dt;}this.numbers=this.numbers.filter(n=>n.life>0);}
 draw(ctx){ctx.save();ctx.globalCompositeOperation='lighter';for(const r of this.rings){ctx.globalAlpha=clamp(r.life);ctx.strokeStyle=r.color==='gold'?'#ffcd7a':'#9defff';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(r.x,r.y,r.r,r.r*.48,0,0,Math.PI*2);ctx.stroke();}for(const p of this.particles){ctx.globalAlpha=clamp(p.life*1.7);ctx.fillStyle=p.color==='gold'?'#ffd889':'#91dfff';ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill();}ctx.restore();for(const n of this.numbers){ctx.save();ctx.globalAlpha=clamp(n.life*2);ctx.fillStyle=n.color==='gold'?'#ffde9b':'#c2f4ff';ctx.strokeStyle='#122035';ctx.lineWidth=4;ctx.font='bold 34px serif';ctx.textAlign='center';ctx.strokeText('-'+n.n,n.x,n.y);ctx.fillText('-'+n.n,n.x,n.y);ctx.restore();}}
}
export function sword(ctx,x,y,angle,length=80,alpha=1){ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.globalAlpha=alpha;ctx.globalCompositeOperation='lighter';const g=ctx.createLinearGradient(-length*1.8,0,length*.3,0);g.addColorStop(0,'#60bfff00');g.addColorStop(.65,'#83d5ff55');g.addColorStop(1,'#dafbff');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(length*.55,0);ctx.lineTo(-length*.45,-4);ctx.lineTo(-length*1.8,0);ctx.lineTo(-length*.45,4);ctx.closePath();ctx.fill();ctx.strokeStyle='#ddfcff';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(-length*.5,0);ctx.lineTo(length*.55,0);ctx.stroke();ctx.strokeStyle='#88dcff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-length*.3,-6);ctx.lineTo(-length*.3,6);ctx.stroke();ctx.restore();}
export function makeSwordField(){return Array.from({length:100},(_,i)=>({x:85+Math.random()*650,y:125+Math.random()*320,angle:(Math.random()-.5)*.2,size:35+Math.random()*35,delay:(i%12)*.043+(Math.random()*.12),bend:Math.random()*100-50}));}
export function drawSwordField(ctx,field,t){let launched=0;for(let i=0;i<field.length;i++){const s=field[i],appear=clamp((t-.2-i*.002)*2),flight=clamp((t-1.3-s.delay)/.8);if(!appear)continue;if(flight>=1)continue;const x=lerp(s.x,1045,flight),y=lerp(s.y,455,flight)+Math.sin(flight*Math.PI)*s.bend;const a=flight>0?Math.atan2(455-s.y,1045-s.x):s.angle;const alpha=appear*(flight>.88?(1-flight)/.12:1);sword(ctx,x,y,a,s.size*(flight>0?1.4:1),alpha);if(flight>0)launched++;}return launched;}
export function drawDragon(ctx,img,t,enemyX){const fly=clamp((t-.65)/1.25),fade=clamp((3.05-t)/.8);if(t<.55||t>3.05)return;const growth=ease(clamp((t-.55)/.65)),headX=lerp(335,enemyX+105,ease(fly)),width=780*growth,height=width*.333,y=382+Math.sin(t*5)*9;ctx.save();ctx.globalAlpha=growth*fade;ctx.globalCompositeOperation='lighter';ctx.shadowColor='#ffb533';ctx.shadowBlur=18;const strips=52;for(let i=0;i<strips;i++){const fraction=i/strips,sx=img.width*fraction,sw=img.width/strips+1,x=headX-width+width*fraction,w=width/strips+1;const wave=Math.sin(fraction*Math.PI*3-t*9)*17*(1-fraction);ctx.drawImage(img,sx,0,sw,img.height,x,y-height*.5+wave,w,height);}ctx.restore();}
