import{loadAssets,clamp,lerp,ease}from'./assets.js';
import{Effects,makeSwordField}from'./fx.js';
import{Renderer}from'./render.js';
import{setSound,soundOn,tone,impact}from'./audio.js';
const $=s=>document.querySelector(s),buttons=[...document.querySelectorAll('[data-skill]')],fx=new Effects();
const fighter=(x,max)=>({x,baseX:x,hp:max,max,pose:'idle',frame:0,lean:0,flash:0,ghost:0,hurt:0});
const g={hero:fighter(270,1200),enemy:fighter(1010,2800),fx,action:null,combo:0,ready:false,entered:false,counter:null,won:false,totalDamage:0};
const durations={dragon:3.35,swords:3.55,palm:1.3};
function hud(){for(const[k,f]of[['hero',g.hero],['enemy',g.enemy]]){$('#'+k+'-health').style.width=(f.hp/f.max*100)+'%';$('#'+k+'-hp').textContent=Math.ceil(f.hp)+' / '+f.max;}buttons.forEach(b=>b.disabled=!g.entered||!!g.action||!!g.counter||g.won);}
function status(text){$('#status').textContent=text;}
function showTitle(kind){const el=$('#skill-title');el.className='skill-title show '+kind;el.querySelector('span').textContent=kind==='dragon'?'降龙十八掌':'万剑归宗';el.querySelector('small').textContent=kind==='dragon'?'亢龙有悔':'万剑同御 · 剑气归宗';}
function hideTitle(){$('#skill-title').classList.remove('show');}
function start(kind){if(!g.entered||g.action||g.counter||g.won||!durations[kind])return;g.combo=0;g.action={kind,t:0,duration:durations[kind],hits:0,field:kind==='swords'?makeSwordField():null};g.hero.pose=kind==='swords'?'sword':'palm';g.hero.frame=0;status(kind==='dragon'?'掌劲凝聚，金龙出海':kind==='swords'?'剑阵凝聚，万剑齐发':'踏步出掌');if(kind!=='palm')showTitle(kind);tone(kind==='swords'?260:85,kind==='swords'?1100:250,.8,.08,'triangle');hud();}
function hit(n,kind='gold',big=false){const f=g.enemy;f.hp=Math.max(0,f.hp-n);f.hurt=.5;f.pose='hurt';f.flash=.15;f.x+=big?50:9;g.combo++;g.totalDamage+=n;fx.burst(f.x,445,big?90:18,kind,big?1.6:.8);fx.ring(f.x,445,kind,big?210:65);fx.damage(f.x+Math.random()*40-20,350,n,kind);fx.shake=big?22:7;fx.flash=big?.6:.1;fx.hitstop=big?.08:.025;impact(big);hud();}
function reset(){g.hero=fighter(270,1200);g.enemy=fighter(1010,2800);g.action=null;g.counter=null;g.combo=0;g.won=false;g.totalDamage=0;fx.clear();hideTitle();buttons.forEach(b=>b.querySelector('i').style.transform='scaleX(0)');status('选择招式，开始切磋');hud();}
function update(dt,time){fx.update(dt);for(const f of[g.hero,g.enemy]){f.flash=Math.max(0,f.flash-dt);if(f.hurt>0){f.hurt-=dt;f.pose='hurt';f.frame=Math.min(3,Math.floor((.5-f.hurt)/.5*4));f.lean=-.07*Math.sin(f.hurt*14);if(f.hurt<=0){f.pose='idle';f.lean=0;}}if(f.pose==='idle')f.x=lerp(f.x,f.baseX,Math.min(1,dt*5));}if(fx.hitstop>0)return;
 const a=g.action;if(a){a.t+=dt;const t=a.t,h=g.hero;buttons.forEach(b=>b.querySelector('i').style.transform='scaleX('+clamp(1-t/a.duration)+')');
 if(a.kind==='dragon'){h.pose=t<2.6?'palm':'idle';h.frame=t<.5?0:t<.8?1:t<2.2?2:3;h.x=270+ease(clamp(t/.8))*35;h.ghost=t>.55&&t<1.2?1:0;if(t<1.3&&Math.random()<.7)fx.burst(h.x+70,435,2,'gold',.3);if(t>=1.85&&!a.hits){a.hits=1;hit(420,'gold',true);status('金龙命中 · 420 点伤害');}}
 if(a.kind==='swords'){h.pose=t<2.7?'sword':'idle';h.frame=t<.6?0:t<1.3?1:t<2.6?2:3;h.x=270;h.ghost=0;const hits=Math.min(10,Math.max(0,Math.floor((t-1.85)/.085)+1));while(a.hits<hits){a.hits++;hit(42,'blue');status('剑气命中 · '+a.hits+' 连击');}}
 if(a.kind==='palm'){h.pose=t<.85?'palm':'idle';h.frame=t<.2?0:t<.35?1:t<.65?2:3;const p=clamp(t/.55);h.x=t<.55?lerp(270,g.enemy.baseX-175,ease(p)):lerp(g.enemy.baseX-175,270,ease(clamp((t-.55)/.65)));h.ghost=t<.6?1:0;if(t>=.48&&!a.hits){a.hits=1;hit(65,'gold');status('出掌命中 · 65 点伤害');}}
 if(t>1.3)hideTitle();if(t>=a.duration){g.action=null;h.pose='idle';h.ghost=0;h.x=h.baseX;buttons.forEach(b=>b.querySelector('i').style.transform='scaleX(0)');if(g.enemy.hp<=0){g.won=true;status('切磋获胜 · 点击重置再次演武');}else{g.counter={t:0,hit:false};status('对手蓄力还击');}hud();}}
 if(g.counter){const a=g.counter;a.t+=dt;const t=a.t,f=g.enemy;f.pose='palm';f.frame=t<.35?0:t<.6?1:t<.95?2:3;f.x=t<.6?lerp(f.baseX,455,ease(clamp(t/.6))):lerp(455,f.baseX,ease(clamp((t-.6)/.65)));f.ghost=t>.3&&t<.8?1:0;if(t>.62&&!a.hit){a.hit=true;g.hero.hp=Math.max(0,g.hero.hp-35);g.hero.hurt=.5;g.hero.flash=.15;fx.burst(300,445,20,'blue',.7);fx.damage(270,350,35,'blue');fx.shake=6;impact();status('对手还击 · 受到 35 点伤害');hud();}if(t>1.3){g.counter=null;f.pose='idle';f.ghost=0;f.x=f.baseX;if(g.hero.hp<=0){g.won=true;status('切磋结束 · 点击重置再次演武');}else status('选择招式，继续切磋');hud();}}
}
buttons.forEach(b=>b.addEventListener('click',()=>start(b.dataset.skill)));
$('#reset').addEventListener('click',reset);
$('#enter').addEventListener('click',()=>{g.entered=true;$('#start').classList.add('hidden');$('#reset').disabled=false;status('选择招式，开始切磋');hud();});
$('#sound').addEventListener('click',()=>{try{setSound(!soundOn());$('#sound').textContent='音效：'+(soundOn()?'开':'关');$('#sound').setAttribute('aria-label',soundOn()?'关闭音效':'开启音效');}catch{status('当前浏览器暂不支持音效');}});
$('#fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('.arena').requestFullscreen();}catch{status('当前浏览器不支持全屏，请横屏试玩');}});
window.addEventListener('keydown',e=>{if(e.repeat||e.altKey||e.ctrlKey||e.metaKey)return;const kind={'1':'dragon','2':'swords','3':'palm'}[e.key];if(kind){e.preventDefault();start(kind);}});
let installEvent=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;$('#install').hidden=false;});$('#install').addEventListener('click',async()=>{if(!installEvent)return;await installEvent.prompt();installEvent=null;$('#install').hidden=true;});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=20260930c').catch(()=>{});
try{const assets=await loadAssets();const renderer=new Renderer($('#battle'),assets);g.ready=true;$('#load-message').textContent='人物与场景已就绪';$('#enter').disabled=false;status('准备就绪');let last=performance.now();document.addEventListener('visibilitychange',()=>{last=performance.now();});const loop=now=>{let dt=Math.min(2,Math.max(0,(now-last)/1000));last=now;if(!document.hidden)update(dt,now/1000);renderer.draw(g,now/1000);$('#battle').dataset.phase=g.action?g.action.kind+':'+g.action.t.toFixed(2):g.counter?'counter':'idle';requestAnimationFrame(loop);};requestAnimationFrame(loop);window.__duel={getState:()=>({ready:g.ready,entered:g.entered,heroHP:g.hero.hp,enemyHP:g.enemy.hp,action:g.action?.kind??null,actionTime:g.action?.t??0,combo:g.combo,totalDamage:g.totalDamage,counter:!!g.counter,won:g.won})};}catch(error){$('#load-message').textContent=error.message+'，请刷新重试';status('载入失败');console.error(error);}
